name: Push a branch de feature
run-name: Push a branch de feature

env:
  APPLICATION_NAME: ${{ github.event.repository.name }}

on:
  push:
    branches:
      - 'feature/*'

jobs:
  Build-Docker-Image:

    if: github.event.before != '0000000000000000000000000000000000000000'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build imagen docker con comandos
        run: docker build -t ${{ env.APPLICATION_NAME }}:snapshot-${{ github.event.head_commit.timestamp }} .

