name: PR con destino develop
run-name: PR con destino develop

env:
  APPLICATION_NAME: ${{ github.event.repository.name }}

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  Build-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set timestamp
        run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> "$GITHUB_ENV"

      - name: Build imagen docker con comandos
        run: docker build -t ${{ env.APPLICATION_NAME }}:snapshot-$TIMESTAMP .

